sudo: required
services:
  - docker

before_install:
  - docker build -t nsksivadocker/docker-react -f Dockerfile.dev .

script:
  - docker run nsksivadocker/docker-react npm run test --env=jsdom --coverage