sudo: required
services:
  - docker

before_install:
  - docker build -t nsksivadocker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nsksivadocker/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-657963648172"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
      secure: $AWS_ACCESS_SECRET

  